// <auto-generated />
using System;
using GoRiZa_Inventar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoRiZa_Inventar.Migrations
{
    [DbContext(typeof(GoRiZa_InventarContext))]
    [Migration("20230710120435_Update")]
    partial class Update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoRiZa_Inventar.Model.Benutzer", b =>
                {
                    b.Property<int>("BenutzerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BenutzerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BenutzerId");

                    b.ToTable("Benutzers");
                });

            modelBuilder.Entity("GoRiZa_Inventar.Model.Computer", b =>
                {
                    b.Property<int>("ComputerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComputerId"));

                    b.Property<int?>("BenutzerId")
                        .HasColumnType("int");

                    b.Property<int?>("GegenstandId")
                        .HasColumnType("int");

                    b.HasKey("ComputerId");

                    b.HasIndex("BenutzerId");

                    b.HasIndex("GegenstandId");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("GoRiZa_Inventar.Model.Gegenstand", b =>
                {
                    b.Property<int>("GegenstandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GegenstandId"));

                    b.Property<int>("Anzahl")
                        .HasColumnType("int");

                    b.Property<string>("Beschreib")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GegenstandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KategorieId")
                        .HasColumnType("int");

                    b.HasKey("GegenstandId");

                    b.HasIndex("KategorieId");

                    b.ToTable("Gegs");
                });

            modelBuilder.Entity("GoRiZa_Inventar.Model.Kategorie", b =>
                {
                    b.Property<int>("KategorieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategorieId"));

                    b.Property<string>("KategorieName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KategorieId");

                    b.ToTable("Kategories");
                });

            modelBuilder.Entity("GoRiZa_Inventar.Model.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<int?>("GegenstandId")
                        .HasColumnType("int");

                    b.Property<int>("Lagerbestand")
                        .HasColumnType("int");

                    b.HasKey("MaterialId");

                    b.HasIndex("GegenstandId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("GoRiZa_Inventar.Model.Raum", b =>
                {
                    b.Property<int>("RaumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RaumId"));

                    b.Property<string>("RaumName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RaumId");

                    b.ToTable("Raums");
                });

            modelBuilder.Entity("GoRiZa_Inventar.Model.RaumGegenstand", b =>
                {
                    b.Property<int>("RaumGegenstandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RaumGegenstandId"));

                    b.Property<int>("GegenstandId")
                        .HasColumnType("int");

                    b.Property<int>("RaumId")
                        .HasColumnType("int");

                    b.HasKey("RaumGegenstandId");

                    b.HasIndex("GegenstandId");

                    b.ToTable("RaumGegenstands");
                });

            modelBuilder.Entity("GoRiZa_Inventar.Model.Computer", b =>
                {
                    b.HasOne("GoRiZa_Inventar.Model.Benutzer", null)
                        .WithMany("ComputerList")
                        .HasForeignKey("BenutzerId");

                    b.HasOne("GoRiZa_Inventar.Model.Gegenstand", null)
                        .WithMany("ComputerList")
                        .HasForeignKey("GegenstandId");
                });

            modelBuilder.Entity("GoRiZa_Inventar.Model.Gegenstand", b =>
                {
                    b.HasOne("GoRiZa_Inventar.Model.Kategorie", null)
                        .WithMany("GegenstandList")
                        .HasForeignKey("KategorieId");
                });

            modelBuilder.Entity("GoRiZa_Inventar.Model.Material", b =>
                {
                    b.HasOne("GoRiZa_Inventar.Model.Gegenstand", null)
                        .WithMany("MaterialList")
                        .HasForeignKey("GegenstandId");
                });

            modelBuilder.Entity("GoRiZa_Inventar.Model.RaumGegenstand", b =>
                {
                    b.HasOne("GoRiZa_Inventar.Model.Gegenstand", null)
                        .WithMany("RaumList")
                        .HasForeignKey("GegenstandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GoRiZa_Inventar.Model.Benutzer", b =>
                {
                    b.Navigation("ComputerList");
                });

            modelBuilder.Entity("GoRiZa_Inventar.Model.Gegenstand", b =>
                {
                    b.Navigation("ComputerList");

                    b.Navigation("MaterialList");

                    b.Navigation("RaumList");
                });

            modelBuilder.Entity("GoRiZa_Inventar.Model.Kategorie", b =>
                {
                    b.Navigation("GegenstandList");
                });
#pragma warning restore 612, 618
        }
    }
}
